name: Bug Report
description: Create a report to help us improve
title: "[Bug Report]"
labels: [bug]
body:



  - type: textarea
    attributes:
      label: Describe the bug
      description:
      placeholder: |
        A clear and concise description of what the bug is.
    validations:
      required: false

  - type: textarea
    attributes:
      label: To Reproduce
      placeholder: |
        Steps to reproduce the behavior:
        1.Go to '...'
        2.Click on '....'
        3.Scroll down to '....'
        4.See error
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error reports & Screenshots
      placeholder: |
        When the error happened, click at the bottom of the page on Copy Details and paste it here.
    validations:
      required: false


  - type: textarea
    attributes:
      label: Device info
      description: |
        Please provide some information of the device you are using.
      placeholder: |
        App version, OS version, device model, etc...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description:
      placeholder: |
        Add any other context about the problem here.